// (C) 2001-2022 Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License Subscription 
// Agreement, Intel FPGA IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Intel and sold by 
// Intel or its authorized distributors.  Please refer to the applicable 
// agreement for further details.



//
// Intel Agilex HPS AXI Soft IP wrappers.
//

module one_hps_interface_ddr (
    input  wire [4095:0] io48_b_cdata_pb0_in,
    output wire [4095:0] io48_b_iod_pb0_out
);

assign io48_b_iod_pb0_out = io48_b_cdata_pb0_in;

endmodule

`timescale 1 ps / 1 ps
module tennm_hps_mpfe_wrapper #( parameter WDTH = 512 , parameter ADDR = 32 , parameter TILEC = "tilec_bypass" )(
    input  wire           f2s_0_clk,
    input  wire           f2s_0_arlock,
    input  wire           f2s_0_arvalid,
    input  wire           f2s_0_awlock,
    input  wire           f2s_0_awvalid,
    input  wire           f2s_0_bready,
    input  wire [    1:0] f2s_0_port_size_config,
    input  wire           f2s_0_rready,
    input  wire           f2s_0_wlast,
    input  wire           f2s_0_wvalid,
    input  wire           f2s_0_rst_n,
    input  wire [   39:0] f2s_0_araddr,
    input  wire [    1:0] f2s_0_arbar,
    input  wire [    1:0] f2s_0_arburst,
    input  wire [    3:0] f2s_0_arcache,
    input  wire [    1:0] f2s_0_ardomain,
    input  wire [    4:0] f2s_0_arid,
    input  wire [    7:0] f2s_0_arlen,
    input  wire [    2:0] f2s_0_arprot,
    input  wire [    3:0] f2s_0_arqos,
    input  wire [    2:0] f2s_0_arsize,
    input  wire [    3:0] f2s_0_arsnoop,
    input  wire [   39:0] f2s_0_awaddr,
    input  wire [    1:0] f2s_0_awbar,
    input  wire [    1:0] f2s_0_awburst,
    input  wire [    3:0] f2s_0_awcache,
    input  wire [    1:0] f2s_0_awdomain,
    input  wire [    4:0] f2s_0_awid,
    input  wire [  8-1:0] f2s_0_awlen,
    input  wire [    2:0] f2s_0_awprot,
    input  wire [    3:0] f2s_0_awqos,
    input  wire [    2:0] f2s_0_awsize,
    input  wire [    2:0] f2s_0_awsnoop,
    input  wire [  511:0] f2s_0_wdata,
    input  wire [   63:0] f2s_0_wstrb,
    input  wire [    7:0] f2s_0_aruser,
    input  wire [    7:0] f2s_0_awuser,
    input  wire [    9:0] f2s_0_rsb_sid,
    input  wire [    4:0] f2s_0_rsb_ssd,
    input  wire [    9:0] f2s_0_wsb_sid,
    input  wire [    4:0] f2s_0_wsb_ssd,

    output wire            f2s_0_arready,
    output wire            f2s_0_awready,
    output wire            f2s_0_bvalid,
    output wire            f2s_0_rlast,
    output wire            f2s_0_rvalid,
    output wire            f2s_0_wready,
    output wire [     4:0] f2s_0_bid,
    output wire [     1:0] f2s_0_bresp,
    output wire [WDTH-1:0] f2s_0_rdata,
    output wire [     4:0] f2s_0_rid,
    output wire [     1:0] f2s_0_rresp,

    output wire            atb_mpfe_afready,
    input  wire            atb_mpfe_afvalid,
    output wire [     1:0] atb_mpfe_atbytes,
    output wire [    31:0] atb_mpfe_atdata,
    output wire [     6:0] atb_mpfe_atid,
    input  wire            atb_mpfe_atready,
    output wire            atb_mpfe_atvalid,
    input  wire            atb_mpfe_clkenm,
    input  wire            atb_mpfe_syncreqm,
    input  wire            atclk_atb_mpfe,
    input  wire            atresetn_atb_mpfe
);

wire [7:0] arlen;
wire [7:0] awlen;
if (WDTH == 128) begin
    assign arlen[7:0] = f2s_0_arlen[7:0];
    assign awlen[7:0] = f2s_0_awlen[7:0];
end
if (WDTH == 256) begin
    assign arlen[7] = 1'b0;
    assign awlen[7] = 1'b0;
    assign arlen[6:0] = f2s_0_arlen[6:0];
    assign awlen[6:0] = f2s_0_awlen[6:0];
end
if (WDTH == 512) begin
    assign arlen[7:6] = 2'b00;
    assign awlen[7:6] = 2'b00;
    assign arlen[5:0] = f2s_0_arlen[5:0];
    assign awlen[5:0] = f2s_0_awlen[5:0];
end

(* altera_attribute = "-name PRESERVE_FANOUT_FREE_WYSIWYG ON" *) tennm_hps_mpfe f2s_module(
    .f2s_0_clk(f2s_0_clk),
    .f2s_0_arlock(f2s_0_arlock),
    .f2s_0_arvalid(f2s_0_arvalid),
    .f2s_0_awlock(f2s_0_awlock),
    .f2s_0_awvalid(f2s_0_awvalid),
    .f2s_0_bready(f2s_0_bready),
    .f2s_0_port_size_config(f2s_0_port_size_config),
    .f2s_0_rready(f2s_0_rready),
    .f2s_0_wlast(f2s_0_wlast),
    .f2s_0_wvalid(f2s_0_wvalid),
    .f2s_0_araddr(f2s_0_araddr),
    .f2s_0_arbar(f2s_0_arbar),
    .f2s_0_arburst(f2s_0_arburst),
    .f2s_0_arcache(f2s_0_arcache),
    .f2s_0_ardomain(f2s_0_ardomain),
    .f2s_0_arid(f2s_0_arid),
    .f2s_0_arlen(arlen),
    .f2s_0_arprot(f2s_0_arprot),
    .f2s_0_arqos(f2s_0_arqos),
    .f2s_0_arsize(f2s_0_arsize),
    .f2s_0_arsnoop(f2s_0_arsnoop),
    .f2s_0_awaddr(f2s_0_awaddr),
    .f2s_0_awbar(f2s_0_awbar),
    .f2s_0_awburst(f2s_0_awburst),
    .f2s_0_awcache(f2s_0_awcache),
    .f2s_0_awdomain(f2s_0_awdomain),
    .f2s_0_awid(f2s_0_awid),
    .f2s_0_awlen(awlen),
    .f2s_0_awprot(f2s_0_awprot),
    .f2s_0_awqos(f2s_0_awqos),
    .f2s_0_awsize(f2s_0_awsize),
    .f2s_0_awsnoop(f2s_0_awsnoop),
    .f2s_0_wstrb(f2s_0_wstrb),
    .f2s_0_wdata(f2s_0_wdata),
    .f2s_0_aruser(f2s_0_aruser),
    .f2s_0_awuser(f2s_0_awuser),
    .f2s_0_arready(f2s_0_arready),
    .f2s_0_awready(f2s_0_awready),
    .f2s_0_bvalid(f2s_0_bvalid),
    .f2s_0_rlast(f2s_0_rlast),
    .f2s_0_rvalid(f2s_0_rvalid),
    .f2s_0_wready(f2s_0_wready),
    .f2s_0_bid(f2s_0_bid),
    .f2s_0_bresp(f2s_0_bresp),
    .f2s_0_rdata(f2s_0_rdata),
    .f2s_0_rid(f2s_0_rid),
    .f2s_0_rresp(f2s_0_rresp),
    .f2s_0_wsb_sid(f2s_0_wsb_sid),
    .f2s_0_wsb_ssd(f2s_0_wsb_ssd),
    .f2s_0_rsb_sid(f2s_0_rsb_sid),
    .f2s_0_rsb_ssd(f2s_0_rsb_ssd),

    .atb_mpfe_afready(atb_mpfe_afready),
    .atb_mpfe_afvalid(atb_mpfe_afvalid),
    .atb_mpfe_atbytes(atb_mpfe_atbytes),
    .atb_mpfe_atdata(atb_mpfe_atdata),
    .atb_mpfe_atid(atb_mpfe_atid),
    .atb_mpfe_atready(atb_mpfe_atready),
    .atb_mpfe_atvalid(atb_mpfe_atvalid),
    .atb_mpfe_clkenm(atb_mpfe_clkenm),
    .atb_mpfe_syncreqm(atb_mpfe_syncreqm),
    .atclk_atb_mpfe(atclk_atb_mpfe),
    .atresetn_atb_mpfe(atresetn_atb_mpfe));
defparam f2s_module.a_cfg_mpfeintfcsel_tileab_hmc = "tileab_mpfe";
defparam f2s_module.a_cfg_mpfeintfcsel_tilec_hmc = TILEC;

endmodule


 
//////////////////////////////////////////////////////////////////////////////////////////////////////////
//
//
`timescale 1 ps / 1 ps
module tennm_hps_hps_wrapper #( parameter WDTH = 128 , parameter ADDR = 32, parameter SWDTH = 4 )(  
// CLOCKS_RESETS ports
    input  wire          f2s_pending_rst_ack,
    input  wire          f2s_free_clk,
    
    output wire          s2f_rst,
    output wire          s2f_cold_rst,
    output wire          s2f_pending_rst_req,
    output wire          s2f_user_clk0_hio,
    output wire          s2f_user_clk1_hio,
    output wire          s2f_watchdog_rst,

// MPU_EVENTS_STANDBY ports
    input  wire          fpga_eventi,
    
    output wire          fpga_evento,
    output wire [  3:0]  fpga_standbywfe,
    output wire [  3:0]  fpga_standbywfi,

// CTI ports
    input  wire [  7:0]  fpga_ctitrigin,
    input  wire [  7:0]  fpga_ctitrigoutack,
    
    output wire [  7:0]  fpga_ctitrigout,
    output wire [  7:0]  fpga_ctitriginack,

// DEBUG_APB ports
    input  wire [ 31:0]  prdatadbg,
    input  wire          preadydbg,
    input  wire          pslverrdbg,
    input  wire          pclkdbg,
    input  wire          pclkendbg,
    input  wire          dbgapbdisable,
    
    output wire [ 14:0]  paddrdbg,
    output wire          paddr31,
    output wire          penabledbg,
    output wire          pseldbg,
    output wire [ 31:0]  pwdatadbg,
    output wire          pwritedbg,
    output wire          s2f_presetdbgn_to_core,

// STM ports
    input  wire [ 43:0]  cs_hwevents_fpga,
    input  wire          cs_ntrst_fpga,
    input  wire          cs_tck_fpga,
    input  wire          cs_tdi_fpga,
    input  wire          cs_tms_fpga,
    
    output wire          cs_tdo_fpga,
    output wire          cs_tdoen_fpga,

// GP ports
    input  wire [ 31:0]  f2s_gp,

    output wire [ 31:0]  s2f_gp,

// ATB ports
    input  wire          afready_atb_mpfe,
    output wire          afvalid_atb_mpfe,
    input  wire [   1:0] atbytes_atb_mpfe,
    input  wire          atclk_atb_mpfe,
    input  wire [  31:0] atdata_atb_mpfe,
    input  wire [   6:0] atid_atb_mpfe,
    output wire          atready_atb_mpfe,
    input  wire          atresetn_atb_mpfe,
    input  wire          atvalid_atb_mpfe,
    output wire          syncreq_atb_mpfe,

// DMA ports
    input  wire          fpga0_dma_req,
    input  wire          fpga0_dma_single,
    input  wire          fpga1_dma_req,
    input  wire          fpga1_dma_single,
    input  wire          fpga2_dma_req,
    input  wire          fpga2_dma_single,
    input  wire          fpga3_dma_req,
    input  wire          fpga3_dma_single,
    input  wire          fpga4_dma_req,
    input  wire          fpga4_dma_single,
    input  wire          fpga5_dma_req,
    input  wire          fpga5_dma_single,
    input  wire          fpga6_dma_req,
    input  wire          fpga6_dma_single,
    input  wire          fpga7_dma_req,
    input  wire          fpga7_dma_single,
                         
    output wire          fpga0_dma_peri_ack,
    output wire          fpga1_dma_peri_ack,
    output wire          fpga2_dma_peri_ack,
    output wire          fpga3_dma_peri_ack,
    output wire          fpga4_dma_peri_ack,
    output wire          fpga5_dma_peri_ack,
    output wire          fpga6_dma_peri_ack,
    output wire          fpga7_dma_peri_ack,

// s2f_INTERRUPTS ports
    output wire [   7:0] s2f_dma_irq,
    output wire          s2f_dma_irq_abort,
    output wire          s2f_ecc_derr_intr_n,
    output wire          s2f_ecc_serr_irq,
    output wire          s2f_clkmgr_irq,
    output wire          s2f_timer_l4sp_0_irq,
    output wire          s2f_timer_l4sp_1_irq,
    output wire          s2f_timer_sys_0_irq,
    output wire          s2f_timer_sys_1_irq,
    output wire          s2f_sdmmc_irq,
    output wire          s2f_usb0_irq,
    output wire          s2f_usb1_irq,
    output wire          s2f_emac0_irq,
    output wire          s2f_emac1_irq,
    output wire          s2f_emac2_irq,
    output wire          s2f_i2c_emac0_irq,
    output wire          s2f_i2c_emac1_irq,
    output wire          s2f_i2c_emac2_irq,
    output wire          s2f_spim0_irq,
    output wire          s2f_spim1_irq,
    output wire          s2f_spis0_irq,
    output wire          s2f_spis1_irq,
    output wire          s2f_i2c0_irq,
    output wire          s2f_i2c1_irq,
    output wire          s2f_uart0_irq,
    output wire          s2f_uart1_irq,
    output wire          s2f_nand_irq,
    output wire          s2f_gpio0_irq,
    output wire          s2f_gpio1_irq,
    output wire          s2f_wdog0_irq,
    output wire          s2f_wdog1_irq,
    output wire          s2f_wdog2_irq,
    output wire          s2f_wdog3_irq,

// f2s_INTERRUPTS ports
    input  wire [ 63:0]  f2s_fpga_irq,

// HPS_IO ports
    input  wire          HPS_IOA_1_I,
    input  wire          HPS_IOA_2_I,
    input  wire          HPS_IOA_3_I,
    input  wire          HPS_IOA_4_I,
    input  wire          HPS_IOA_5_I,
    input  wire          HPS_IOA_6_I,
    input  wire          HPS_IOA_7_I,
    input  wire          HPS_IOA_8_I,
    input  wire          HPS_IOA_9_I,
    input  wire          HPS_IOA_10_I,
    input  wire          HPS_IOA_11_I,
    input  wire          HPS_IOA_12_I,
    input  wire          HPS_IOA_13_I,
    input  wire          HPS_IOA_14_I,
    input  wire          HPS_IOA_15_I,
    input  wire          HPS_IOA_16_I,
    input  wire          HPS_IOA_17_I,
    input  wire          HPS_IOA_18_I,
    input  wire          HPS_IOA_19_I,
    input  wire          HPS_IOA_20_I,
    input  wire          HPS_IOA_21_I,
    input  wire          HPS_IOA_22_I,
    input  wire          HPS_IOA_23_I,
    input  wire          HPS_IOA_24_I,
    input  wire          HPS_IOB_1_I,
    input  wire          HPS_IOB_2_I,
    input  wire          HPS_IOB_3_I,
    input  wire          HPS_IOB_4_I,
    input  wire          HPS_IOB_5_I,
    input  wire          HPS_IOB_6_I,
    input  wire          HPS_IOB_7_I,
    input  wire          HPS_IOB_8_I,
    input  wire          HPS_IOB_9_I,
    input  wire          HPS_IOB_10_I,
    input  wire          HPS_IOB_11_I,
    input  wire          HPS_IOB_12_I,
    input  wire          HPS_IOB_13_I,
    input  wire          HPS_IOB_14_I,
    input  wire          HPS_IOB_15_I,
    input  wire          HPS_IOB_16_I,
    input  wire          HPS_IOB_17_I,
    input  wire          HPS_IOB_18_I,
    input  wire          HPS_IOB_19_I,
    input  wire          HPS_IOB_20_I,
    input  wire          HPS_IOB_21_I,
    input  wire          HPS_IOB_22_I,
    input  wire          HPS_IOB_23_I,
    input  wire          HPS_IOB_24_I,

    output wire          HPS_IOA_1_O,
    output wire          HPS_IOA_2_O,
    output wire          HPS_IOA_3_O,
    output wire          HPS_IOA_4_O,
    output wire          HPS_IOA_5_O,
    output wire          HPS_IOA_6_O,
    output wire          HPS_IOA_7_O,
    output wire          HPS_IOA_8_O,
    output wire          HPS_IOA_9_O,
    output wire          HPS_IOA_10_O,
    output wire          HPS_IOA_11_O,
    output wire          HPS_IOA_12_O,
    output wire          HPS_IOA_13_O,
    output wire          HPS_IOA_14_O,
    output wire          HPS_IOA_15_O,
    output wire          HPS_IOA_16_O,
    output wire          HPS_IOA_17_O,
    output wire          HPS_IOA_18_O,
    output wire          HPS_IOA_19_O,
    output wire          HPS_IOA_20_O,
    output wire          HPS_IOA_21_O,
    output wire          HPS_IOA_22_O,
    output wire          HPS_IOA_23_O,
    output wire          HPS_IOA_24_O,
    output wire          HPS_IOB_1_O,
    output wire          HPS_IOB_2_O,
    output wire          HPS_IOB_3_O,
    output wire          HPS_IOB_4_O,
    output wire          HPS_IOB_5_O,
    output wire          HPS_IOB_6_O,
    output wire          HPS_IOB_7_O,
    output wire          HPS_IOB_8_O,
    output wire          HPS_IOB_9_O,
    output wire          HPS_IOB_10_O,
    output wire          HPS_IOB_11_O,
    output wire          HPS_IOB_12_O,
    output wire          HPS_IOB_13_O,
    output wire          HPS_IOB_14_O,
    output wire          HPS_IOB_15_O,
    output wire          HPS_IOB_16_O,
    output wire          HPS_IOB_17_O,
    output wire          HPS_IOB_18_O,
    output wire          HPS_IOB_19_O,
    output wire          HPS_IOB_20_O,
    output wire          HPS_IOB_21_O,
    output wire          HPS_IOB_22_O,
    output wire          HPS_IOB_23_O,
    output wire          HPS_IOB_24_O,

// DFT ports
    input  wire          dft_in_clkod_scanclk,
    input  wire          dft_in_psi_test_clk,
    input  wire          dft_in_tck,
    input  wire          dft_in_ramrpr_chain3_rsclk,
    input  wire          dft_in_mbist_tck,
    input  wire          dft_in_ramrpr_chain1_rsclk,
    input  wire          dft_in_ramrpr_chain5_rsclk,

// EMAC PTP
    input  wire          emac_ptp_ref_clk,

// EMAC0 ports (on FPGA)
    input  wire          emac0_gmii_mdi_i,
    input  wire          emac0_phy_col_i,
    input  wire          emac0_phy_crs_i,
    input  wire          emac0_phy_rxclk_i,
    input  wire [  7:0]  emac0_phy_rxd_i,
    input  wire          emac0_phy_rxdv_i,
    input  wire          emac0_phy_rxer_i,
    input  wire          emac0_phy_txclk_i,
    input  wire          emac0_ptp_aux_ts_trig_i,

    output wire          emac0_gmii_mdc_o,
    output wire          emac0_gmii_mdo_o,
    output wire          emac0_gmii_mdo_o_e,
    output wire [  1:0]  emac0_phy_mac_speed_o,
    output wire          emac0_phy_txclk_o_hio,
    output wire [  7:0]  emac0_phy_txd_gmii_o,
    output wire [  7:0]  emac0_phy_txd_o,
    output wire          emac0_phy_txen_o,
    output wire          emac0_phy_txer_o,
    output wire          emac0_ptp_pps_o,
    output wire          emac0_rst_clk_rx_n_o,
    output wire          emac0_rst_clk_tx_n_o,
    output wire          s2f_emac0_ptp_tstmp_data,
    output wire          s2f_emac0_ptp_tstmp_en,

// EMAC1 ports (on FPGA)
    input  wire          emac1_gmii_mdi_i,
    input  wire          emac1_phy_col_i,
    input  wire          emac1_phy_crs_i,
    input  wire          emac1_phy_rxclk_i,
    input  wire [  7:0]  emac1_phy_rxd_i,
    input  wire          emac1_phy_rxdv_i,
    input  wire          emac1_phy_rxer_i,
    input  wire          emac1_phy_txclk_i,
    input  wire          emac1_ptp_aux_ts_trig_i,

    output wire          emac1_gmii_mdc_o,
    output wire          emac1_gmii_mdo_o,
    output wire          emac1_gmii_mdo_o_e,
    output wire [  1:0]  emac1_phy_mac_speed_o,
    output wire          emac1_phy_txclk_o_hio,
    output wire [  7:0]  emac1_phy_txd_gmii_o,
    output wire [  7:0]  emac1_phy_txd_o,
    output wire          emac1_phy_txen_o,
    output wire          emac1_phy_txer_o,
    output wire          emac1_ptp_pps_o,
    output wire          emac1_rst_clk_rx_n_o,
    output wire          emac1_rst_clk_tx_n_o,
    output wire          s2f_emac1_ptp_tstmp_data,
    output wire          s2f_emac1_ptp_tstmp_en,

// EMAC2 ports (on FPGA)
    input  wire          emac2_gmii_mdi_i,
    input  wire          emac2_phy_col_i,
    input  wire          emac2_phy_crs_i,
    input  wire          emac2_phy_rxclk_i,
    input  wire [  7:0]  emac2_phy_rxd_i,
    input  wire          emac2_phy_rxdv_i,
    input  wire          emac2_phy_rxer_i,
    input  wire          emac2_phy_txclk_i,
    input  wire          emac2_ptp_aux_ts_trig_i,

    output wire          emac2_gmii_mdc_o,
    output wire          emac2_gmii_mdo_o,
    output wire          emac2_gmii_mdo_o_e,
    output wire [  1:0]  emac2_phy_mac_speed_o,
    output wire          emac2_phy_txclk_o_hio,
    output wire [  7:0]  emac2_phy_txd_gmii_o,
    output wire [  7:0]  emac2_phy_txd_o,
    output wire          emac2_phy_txen_o,
    output wire          emac2_phy_txer_o,
    output wire          emac2_ptp_pps_o,
    output wire          emac2_rst_clk_rx_n_o,
    output wire          emac2_rst_clk_tx_n_o,
    output wire          s2f_emac2_ptp_tstmp_data,
    output wire          s2f_emac2_ptp_tstmp_en,

// NAND ports (on FPGA)
    input  wire [ 15:0]  nand_adq_i,
    input  wire [  3:0]  nand_rdy_busy_i,

    output wire [ 15:0]  nand_adq_o,
    output wire          nand_adq_oe,
    output wire          nand_ale_o,
    output wire [  3:0]  nand_ce_n_o,
    output wire          nand_cle_o,
    output wire          nand_re_n_o,
    output wire          nand_we_n_o,
    output wire          nand_wp_n_o,

// SDMMC ports (on FPGA)
    input  wire          sdmmc_card_intn_i,
    input  wire          sdmmc_cdn_i,
    input  wire          sdmmc_cmd_i,
    input  wire [  7:0]  sdmmc_data_i,
    input  wire          sdmmc_wp_i,

    output wire          sdmmc_cclk_o,
    output wire          sdmmc_cmd_o,
    output wire          sdmmc_cmd_oe,
    output wire [  7:0]  sdmmc_data_o,
    output wire [  7:0]  sdmmc_data_oe,
    output wire          sdmmc_pwr_ena_o,
    output wire          sdmmc_rstn_o,
    output wire          sdmmc_vs_o,

// SPIM0 (on FPGA)
    input  wire          spim0_miso_i,
    input  wire          spim0_ss_in_n,

    output wire          spim0_mosi_o,
    output wire          spim0_mosi_oe,
    output wire          spim0_sclk_out_hio,
    output wire          spim0_ss0_n_o,
    output wire          spim0_ss1_n_o,
    output wire          spim0_ss2_n_o,
    output wire          spim0_ss3_n_o,

// SPIM1 (on FPGA)
    input  wire          spim1_miso_i,
    input  wire          spim1_ss_in_n,

    output wire          spim1_mosi_o,
    output wire          spim1_mosi_oe,
    output wire          spim1_sclk_out_hio,
    output wire          spim1_ss0_n_o,
    output wire          spim1_ss1_n_o,
    output wire          spim1_ss2_n_o,
    output wire          spim1_ss3_n_o,

// SPIS0 (on FPGA)
    input  wire          spis0_clk,
    input  wire          spis0_mosi_i,
    input  wire          spis0_ss_in_n,

    output wire          spis0_miso_o,
    output wire          spis0_miso_oe,

// SPIS1 (on FPGA)
    input  wire          spis1_clk,
    input  wire          spis1_mosi_i,
    input  wire          spis1_ss_in_n,

    output wire          spis1_miso_o,
    output wire          spis1_miso_oe,

// UART0 (on FPGA)
    input  wire          uart0_cts_n,
    input  wire          uart0_dcd_n,
    input  wire          uart0_dsr_n,
    input  wire          uart0_ri_n,
    input  wire          uart0_rx,
    
    output wire          uart0_dtr_n,
    output wire          uart0_out1_n,
    output wire          uart0_out2_n,
    output wire          uart0_rts_n,
    output wire          uart0_tx,

// UART1 (on FPGA)
    input  wire          uart1_cts_n,
    input  wire          uart1_dcd_n,
    input  wire          uart1_dsr_n,
    input  wire          uart1_ri_n,
    input  wire          uart1_rx,
    
    output wire          uart1_dtr_n,
    output wire          uart1_out1_n,
    output wire          uart1_out2_n,
    output wire          uart1_rts_n,
    output wire          uart1_tx,

// I2C0 (on FPGA)
    input  wire          i2c0_scl_i,
    input  wire          i2c0_sda_i,

    output wire          i2c0_scl_oe,
    output wire          i2c0_sda_oe,

// I2C1 (on FPGA)
    input  wire          i2c1_scl_i,
    input  wire          i2c1_sda_i,

    output wire          i2c1_scl_oe,
    output wire          i2c1_sda_oe,

// I2C_EMAC0 (on FPGA)
    input  wire          i2c_emac0_scl_i,
    input  wire          i2c_emac0_sda_i,

    output wire          i2c_emac0_scl_oe,
    output wire          i2c_emac0_sda_oe,

// I2C_EMAC1 (on FPGA)
    input  wire          i2c_emac1_scl_i,
    input  wire          i2c_emac1_sda_i,

    output wire          i2c_emac1_scl_oe,
    output wire          i2c_emac1_sda_oe,

// I2C_EMAC2 (on FPGA)
    input  wire          i2c_emac2_scl_i,
    input  wire          i2c_emac2_sda_i,

    output wire          i2c_emac2_scl_oe,
    output wire          i2c_emac2_sda_oe,

// TRACE (on FPGA)
    input  wire          tpiu_trace_clkin,
    input  wire          tpiu_trace_ctl,

    output wire          tpiu_trace_clk_hio,
    output wire [ 63:0]  tpiu_trace_data,

// H2F ports 
    input  wire            soc2fpga_ar_ready,
    input  wire            soc2fpga_aw_ready,
    input  wire            soc2fpga_b_valid,
    input  wire            soc2fpga_clk,
    input  wire            soc2fpga_port_size_config_0,
    input  wire            soc2fpga_port_size_config_1,
    input  wire            soc2fpga_r_last,
    input  wire            soc2fpga_r_valid,
    input  wire            soc2fpga_w_ready,
    input  wire [    3:0]  soc2fpga_b_id,
    input  wire [    1:0]  soc2fpga_b_resp,
    input  wire [  127:0]  soc2fpga_r_data,
    input  wire [    3:0]  soc2fpga_r_id,
    input  wire [    1:0]  soc2fpga_r_resp,
    input  wire            soc2fpga_rst_n,
        
    output wire              soc2fpga_ar_lock,
    output wire              soc2fpga_ar_valid,
    output wire              soc2fpga_aw_lock,
    output wire              soc2fpga_aw_valid,
    output wire              soc2fpga_b_ready,
    output wire              soc2fpga_r_ready,
    output wire              soc2fpga_w_last,
    output wire              soc2fpga_w_valid,
    output wire [ ADDR-1:0]  soc2fpga_ar_addr,
    output wire [      1:0]  soc2fpga_ar_burst,
    output wire [      3:0]  soc2fpga_ar_cache,
    output wire [      3:0]  soc2fpga_ar_id,
    output wire [      7:0]  soc2fpga_ar_len,
    output wire [      2:0]  soc2fpga_ar_prot,
    output wire [      2:0]  soc2fpga_ar_size,
    output wire [ ADDR-1:0]  soc2fpga_aw_addr,
    output wire [      1:0]  soc2fpga_aw_burst,
    output wire [      3:0]  soc2fpga_aw_cache,
    output wire [      3:0]  soc2fpga_aw_id,
    output wire [      7:0]  soc2fpga_aw_len,
    output wire [      2:0]  soc2fpga_aw_prot,
    output wire [      2:0]  soc2fpga_aw_size,
    output wire [ WDTH-1:0]  soc2fpga_w_data,
    output wire [SWDTH-1:0]  soc2fpga_w_strb,

// LWH2F ports
    input  wire          lwsoc2fpga_ar_ready,
    input  wire          lwsoc2fpga_aw_ready,
    input  wire          lwsoc2fpga_b_valid,
    input  wire          lwsoc2fpga_clk,
    input  wire          lwsoc2fpga_port_size_config_0,
    input  wire          lwsoc2fpga_port_size_config_1,
    input  wire          lwsoc2fpga_r_last,
    input  wire          lwsoc2fpga_r_valid,
    input  wire          lwsoc2fpga_w_ready,
    input  wire          lwsoc2fpga_rst_n, 
    input  wire [  3:0]  lwsoc2fpga_b_id,
    input  wire [  1:0]  lwsoc2fpga_b_resp,
    input  wire [ 31:0]  lwsoc2fpga_r_data,
    input  wire [  3:0]  lwsoc2fpga_r_id,
    input  wire [  1:0]  lwsoc2fpga_r_resp,
    output wire          lwsoc2fpga_ar_lock,
    output wire          lwsoc2fpga_ar_valid,
    output wire          lwsoc2fpga_aw_lock,
    output wire          lwsoc2fpga_aw_valid,
    output wire          lwsoc2fpga_b_ready,
    output wire          lwsoc2fpga_r_ready,
    output wire          lwsoc2fpga_w_last,
    output wire          lwsoc2fpga_w_valid,
    output wire [ 31:0]  lwsoc2fpga_ar_addr,
    output wire [  1:0]  lwsoc2fpga_ar_burst,
    output wire [  3:0]  lwsoc2fpga_ar_cache,
    output wire [  3:0]  lwsoc2fpga_ar_id,
    output wire [  7:0]  lwsoc2fpga_ar_len,
    output wire [  2:0]  lwsoc2fpga_ar_prot,
    output wire [  2:0]  lwsoc2fpga_ar_size,
    output wire [ 31:0]  lwsoc2fpga_aw_addr,
    output wire [  1:0]  lwsoc2fpga_aw_burst,
    output wire [  3:0]  lwsoc2fpga_aw_cache,
    output wire [  3:0]  lwsoc2fpga_aw_id,
    output wire [  7:0]  lwsoc2fpga_aw_len,
    output wire [  2:0]  lwsoc2fpga_aw_prot,
    output wire [  2:0]  lwsoc2fpga_aw_size,
    output wire [ 31:0]  lwsoc2fpga_w_data,
    output wire [  3:0]  lwsoc2fpga_w_strb
);

(* altera_attribute = "-name PRESERVE_FANOUT_FREE_WYSIWYG ON" *) tennm_hps_hps s2f_module(
    .f2s_pending_rst_ack(f2s_pending_rst_ack),
    .f2s_free_clk(f2s_free_clk),
    .s2f_rst(s2f_rst),
    .s2f_cold_rst(s2f_cold_rst),
    .s2f_pending_rst_req(s2f_pending_rst_req),
    .s2f_user_clk0_hio(s2f_user_clk0_hio),
    .s2f_user_clk1_hio(s2f_user_clk1_hio),
    .s2f_watchdog_rst(s2f_watchdog_rst),
    .fpga_eventi(fpga_eventi),
    .fpga_evento(fpga_evento),
    .fpga_standbywfe(fpga_standbywfe),
    .fpga_standbywfi(fpga_standbywfi),
    .prdatadbg(prdatadbg),
    .preadydbg(preadydbg),
    .pslverrdbg(pslverrdbg),
    .pclkdbg(pclkdbg),
    .pclkendbg(pclkendbg),
    .dbgapbdisable(dbgapbdisable),
    .paddrdbg(paddrdbg),
    .paddr31(paddr31),
    .penabledbg(penabledbg),
    .pseldbg(pseldbg),
    .pwdatadbg(pwdatadbg),
    .pwritedbg(pwritedbg),
    .s2f_presetdbgn_to_core(s2f_presetdbgn_to_core),
    .cs_hwevents_fpga(cs_hwevents_fpga),
    .cs_ntrst_fpga(cs_ntrst_fpga),
    .cs_tck_fpga(cs_tck_fpga),
    .cs_tdi_fpga(cs_tdi_fpga),
    .cs_tms_fpga(cs_tms_fpga),
    .cs_tdo_fpga(cs_tdo_fpga),
    .cs_tdoen_fpga(cs_tdoen_fpga),
    .fpga_ctitrigin(fpga_ctitrigin),
    .fpga_ctitrigoutack(fpga_ctitrigoutack),
    .fpga_ctitrigout(fpga_ctitrigout),
    .fpga_ctitriginack(fpga_ctitriginack),
    .f2s_gp(f2s_gp),
    .s2f_gp(s2f_gp),
    .afready_atb_mpfe(afready_atb_mpfe),
    .afvalid_atb_mpfe(afvalid_atb_mpfe),
    .atbytes_atb_mpfe(atbytes_atb_mpfe),
    .atclk_atb_mpfe(atclk_atb_mpfe),
    .atdata_atb_mpfe(atdata_atb_mpfe),
    .atid_atb_mpfe(atid_atb_mpfe),
    .atready_atb_mpfe(atready_atb_mpfe),
    .atresetn_atb_mpfe(atresetn_atb_mpfe),
    .atvalid_atb_mpfe(atvalid_atb_mpfe),
    .syncreq_atb_mpfe(syncreq_atb_mpfe),
    .fpga0_dma_req(fpga0_dma_req),
    .fpga0_dma_single(fpga0_dma_single),
    .fpga1_dma_req(fpga1_dma_req),
    .fpga1_dma_single(fpga1_dma_single),
    .fpga2_dma_req(fpga2_dma_req),
    .fpga2_dma_single(fpga2_dma_single),
    .fpga3_dma_req(fpga3_dma_req),
    .fpga3_dma_single(fpga3_dma_single),
    .fpga4_dma_req(fpga4_dma_req),
    .fpga4_dma_single(fpga4_dma_single),
    .fpga5_dma_req(fpga5_dma_req),
    .fpga5_dma_single(fpga5_dma_single),
    .fpga6_dma_req(fpga6_dma_req),
    .fpga6_dma_single(fpga6_dma_single),
    .fpga7_dma_req(fpga7_dma_req),
    .fpga7_dma_single(fpga7_dma_single),
    .fpga0_dma_peri_ack(fpga0_dma_peri_ack),
    .fpga1_dma_peri_ack(fpga1_dma_peri_ack),
    .fpga2_dma_peri_ack(fpga2_dma_peri_ack),
    .fpga3_dma_peri_ack(fpga3_dma_peri_ack),
    .fpga4_dma_peri_ack(fpga4_dma_peri_ack),
    .fpga5_dma_peri_ack(fpga5_dma_peri_ack),
    .fpga6_dma_peri_ack(fpga6_dma_peri_ack),
    .fpga7_dma_peri_ack(fpga7_dma_peri_ack),
    .s2f_dma_irq(s2f_dma_irq),
    .s2f_dma_irq_abort(s2f_dma_irq_abort),
    .s2f_ecc_derr_intr_n(s2f_ecc_derr_intr_n),
    .s2f_ecc_serr_irq(s2f_ecc_serr_irq),
    .s2f_clkmgr_irq(s2f_clkmgr_irq),
    .s2f_timer_l4sp_0_irq(s2f_timer_l4sp_0_irq),
    .s2f_timer_l4sp_1_irq(s2f_timer_l4sp_1_irq),
    .s2f_timer_sys_0_irq(s2f_timer_sys_0_irq),
    .s2f_timer_sys_1_irq(s2f_timer_sys_1_irq),
    .s2f_sdmmc_irq(s2f_sdmmc_irq),
    .s2f_usb0_irq(s2f_usb0_irq),
    .s2f_usb1_irq(s2f_usb1_irq),
    .s2f_emac0_irq(s2f_emac0_irq),
    .s2f_emac1_irq(s2f_emac1_irq),
    .s2f_emac2_irq(s2f_emac2_irq),
    .s2f_i2c_emac0_irq(s2f_i2c_emac0_irq),
    .s2f_i2c_emac1_irq(s2f_i2c_emac1_irq),
    .s2f_i2c_emac2_irq(s2f_i2c_emac2_irq),
    .s2f_spim0_irq(s2f_spim0_irq),
    .s2f_spim1_irq(s2f_spim1_irq),
    .s2f_spis0_irq(s2f_spis0_irq),
    .s2f_spis1_irq(s2f_spis1_irq),
    .s2f_i2c0_irq(s2f_i2c0_irq),
    .s2f_i2c1_irq(s2f_i2c1_irq),
    .s2f_uart0_irq(s2f_uart0_irq),
    .s2f_uart1_irq(s2f_uart1_irq),
    .s2f_nand_irq(s2f_nand_irq),
    .s2f_gpio0_irq(s2f_gpio0_irq),
    .s2f_gpio1_irq(s2f_gpio1_irq),
    .s2f_wdog0_irq(s2f_wdog0_irq),
    .s2f_wdog1_irq(s2f_wdog1_irq),
    .s2f_wdog2_irq(s2f_wdog2_irq),
    .s2f_wdog3_irq(s2f_wdog3_irq),
    .f2s_fpga_irq(f2s_fpga_irq),
    .hps_ioa_1_bidir_in(HPS_IOA_1_I),
    .hps_ioa_2_bidir_in(HPS_IOA_2_I),
    .hps_ioa_3_bidir_in(HPS_IOA_3_I),
    .hps_ioa_4_bidir_in(HPS_IOA_4_I),
    .hps_ioa_5_bidir_in(HPS_IOA_5_I),
    .hps_ioa_6_bidir_in(HPS_IOA_6_I),
    .hps_ioa_7_bidir_in(HPS_IOA_7_I),
    .hps_ioa_8_bidir_in(HPS_IOA_8_I),
    .hps_ioa_9_bidir_in(HPS_IOA_9_I),
    .hps_ioa_10_bidir_in(HPS_IOA_10_I),
    .hps_ioa_11_bidir_in(HPS_IOA_11_I),
    .hps_ioa_12_bidir_in(HPS_IOA_12_I),
    .hps_ioa_13_bidir_in(HPS_IOA_13_I),
    .hps_ioa_14_bidir_in(HPS_IOA_14_I),
    .hps_ioa_15_bidir_in(HPS_IOA_15_I),
    .hps_ioa_16_bidir_in(HPS_IOA_16_I),
    .hps_ioa_17_bidir_in(HPS_IOA_17_I),
    .hps_ioa_18_bidir_in(HPS_IOA_18_I),
    .hps_ioa_19_bidir_in(HPS_IOA_19_I),
    .hps_ioa_20_bidir_in(HPS_IOA_20_I),
    .hps_ioa_21_bidir_in(HPS_IOA_21_I),
    .hps_ioa_22_bidir_in(HPS_IOA_22_I),
    .hps_ioa_23_bidir_in(HPS_IOA_23_I),
    .hps_ioa_24_bidir_in(HPS_IOA_24_I),
    .hps_iob_1_bidir_in(HPS_IOB_1_I),
    .hps_iob_2_bidir_in(HPS_IOB_2_I),
    .hps_iob_3_bidir_in(HPS_IOB_3_I),
    .hps_iob_4_bidir_in(HPS_IOB_4_I),
    .hps_iob_5_bidir_in(HPS_IOB_5_I),
    .hps_iob_6_bidir_in(HPS_IOB_6_I),
    .hps_iob_7_bidir_in(HPS_IOB_7_I),
    .hps_iob_8_bidir_in(HPS_IOB_8_I),
    .hps_iob_9_bidir_in(HPS_IOB_9_I),
    .hps_iob_10_bidir_in(HPS_IOB_10_I),
    .hps_iob_11_bidir_in(HPS_IOB_11_I),
    .hps_iob_12_bidir_in(HPS_IOB_12_I),
    .hps_iob_13_bidir_in(HPS_IOB_13_I),
    .hps_iob_14_bidir_in(HPS_IOB_14_I),
    .hps_iob_15_bidir_in(HPS_IOB_15_I),
    .hps_iob_16_bidir_in(HPS_IOB_16_I),
    .hps_iob_17_bidir_in(HPS_IOB_17_I),
    .hps_iob_18_bidir_in(HPS_IOB_18_I),
    .hps_iob_19_bidir_in(HPS_IOB_19_I),
    .hps_iob_20_bidir_in(HPS_IOB_20_I),
    .hps_iob_21_bidir_in(HPS_IOB_21_I),
    .hps_iob_22_bidir_in(HPS_IOB_22_I),
    .hps_iob_23_bidir_in(HPS_IOB_23_I),
    .hps_iob_24_bidir_in(HPS_IOB_24_I),
    .hps_ioa_1_bidir_out(HPS_IOA_1_O),
    .hps_ioa_2_bidir_out(HPS_IOA_2_O),
    .hps_ioa_3_bidir_out(HPS_IOA_3_O),
    .hps_ioa_4_bidir_out(HPS_IOA_4_O),
    .hps_ioa_5_bidir_out(HPS_IOA_5_O),
    .hps_ioa_6_bidir_out(HPS_IOA_6_O),
    .hps_ioa_7_bidir_out(HPS_IOA_7_O),
    .hps_ioa_8_bidir_out(HPS_IOA_8_O),
    .hps_ioa_9_bidir_out(HPS_IOA_9_O),
    .hps_ioa_10_bidir_out(HPS_IOA_10_O),
    .hps_ioa_11_bidir_out(HPS_IOA_11_O),
    .hps_ioa_12_bidir_out(HPS_IOA_12_O),
    .hps_ioa_13_bidir_out(HPS_IOA_13_O),
    .hps_ioa_14_bidir_out(HPS_IOA_14_O),
    .hps_ioa_15_bidir_out(HPS_IOA_15_O),
    .hps_ioa_16_bidir_out(HPS_IOA_16_O),
    .hps_ioa_17_bidir_out(HPS_IOA_17_O),
    .hps_ioa_18_bidir_out(HPS_IOA_18_O),
    .hps_ioa_19_bidir_out(HPS_IOA_19_O),
    .hps_ioa_20_bidir_out(HPS_IOA_20_O),
    .hps_ioa_21_bidir_out(HPS_IOA_21_O),
    .hps_ioa_22_bidir_out(HPS_IOA_22_O),
    .hps_ioa_23_bidir_out(HPS_IOA_23_O),
    .hps_ioa_24_bidir_out(HPS_IOA_24_O),
    .hps_iob_1_bidir_out(HPS_IOB_1_O),
    .hps_iob_2_bidir_out(HPS_IOB_2_O),
    .hps_iob_3_bidir_out(HPS_IOB_3_O),
    .hps_iob_4_bidir_out(HPS_IOB_4_O),
    .hps_iob_5_bidir_out(HPS_IOB_5_O),
    .hps_iob_6_bidir_out(HPS_IOB_6_O),
    .hps_iob_7_bidir_out(HPS_IOB_7_O),
    .hps_iob_8_bidir_out(HPS_IOB_8_O),
    .hps_iob_9_bidir_out(HPS_IOB_9_O),
    .hps_iob_10_bidir_out(HPS_IOB_10_O),
    .hps_iob_11_bidir_out(HPS_IOB_11_O),
    .hps_iob_12_bidir_out(HPS_IOB_12_O),
    .hps_iob_13_bidir_out(HPS_IOB_13_O),
    .hps_iob_14_bidir_out(HPS_IOB_14_O),
    .hps_iob_15_bidir_out(HPS_IOB_15_O),
    .hps_iob_16_bidir_out(HPS_IOB_16_O),
    .hps_iob_17_bidir_out(HPS_IOB_17_O),
    .hps_iob_18_bidir_out(HPS_IOB_18_O),
    .hps_iob_19_bidir_out(HPS_IOB_19_O),
    .hps_iob_20_bidir_out(HPS_IOB_20_O),
    .hps_iob_21_bidir_out(HPS_IOB_21_O),
    .hps_iob_22_bidir_out(HPS_IOB_22_O),
    .hps_iob_23_bidir_out(HPS_IOB_23_O),
    .hps_iob_24_bidir_out(HPS_IOB_24_O),
    .dft_in_clkod_scanclk(dft_in_clkod_scanclk),
    .dft_in_psi_test_clk(dft_in_psi_test_clk),
    .dft_in_tck(dft_in_tck),
    .dft_in_ramrpr_chain3_rsclk(dft_in_ramrpr_chain3_rsclk),
    .dft_in_mbist_tck(dft_in_mbist_tck),
    .dft_in_ramrpr_chain1_rsclk(dft_in_ramrpr_chain3_rsclk),
    .dft_in_ramrpr_chain5_rsclk(dft_in_ramrpr_chain5_rsclk),
    .emac_ptp_ref_clk(emac_ptp_ref_clk),
    .emac0_gmii_mdi_i(emac0_gmii_mdi_i),
    .emac0_phy_col_i(emac0_phy_col_i),
    .emac0_phy_crs_i(emac0_phy_crs_i),
    .emac0_phy_rxclk_i(emac0_phy_rxclk_i),
    .emac0_phy_rxd_i(emac0_phy_rxd_i),
    .emac0_phy_rxdv_i(emac0_phy_rxdv_i),
    .emac0_phy_rxer_i(emac0_phy_rxer_i),
    .emac0_phy_txclk_i(emac0_phy_txclk_i),
    .emac0_ptp_aux_ts_trig_i(emac0_ptp_aux_ts_trig_i),
    .emac0_gmii_mdc_o(emac0_gmii_mdc_o),
    .emac0_gmii_mdo_o(emac0_gmii_mdo_o),
    .emac0_gmii_mdo_o_e(emac0_gmii_mdo_o_e),
    .emac0_phy_mac_speed_o(emac0_phy_mac_speed_o),
    .emac0_phy_txclk_o_hio(emac0_phy_txclk_o_hio),
    .emac0_phy_txd_gmii_o(emac0_phy_txd_gmii_o),
    .emac0_phy_txd_o(emac0_phy_txd_o),
    .emac0_phy_txen_o(emac0_phy_txen_o),
    .emac0_phy_txer_o(emac0_phy_txer_o),
    .emac0_ptp_pps_o(emac0_ptp_pps_o),
    .emac0_rst_clk_rx_n_o(emac0_rst_clk_rx_n_o),
    .emac0_rst_clk_tx_n_o(emac0_rst_clk_tx_n_o),
    .s2f_emac0_ptp_tstmp_data(s2f_emac0_ptp_tstmp_data),
    .s2f_emac0_ptp_tstmp_en(s2f_emac0_ptp_tstmp_en),
    .emac1_gmii_mdi_i(emac1_gmii_mdi_i),
    .emac1_phy_col_i(emac1_phy_col_i),
    .emac1_phy_crs_i(emac1_phy_crs_i),
    .emac1_phy_rxclk_i(emac1_phy_rxclk_i),
    .emac1_phy_rxd_i(emac1_phy_rxd_i),
    .emac1_phy_rxdv_i(emac1_phy_rxdv_i),
    .emac1_phy_rxer_i(emac1_phy_rxer_i),
    .emac1_phy_txclk_i(emac1_phy_txclk_i),
    .emac1_ptp_aux_ts_trig_i(emac1_ptp_aux_ts_trig_i),
    .emac1_gmii_mdc_o(emac1_gmii_mdc_o),
    .emac1_gmii_mdo_o(emac1_gmii_mdo_o),
    .emac1_gmii_mdo_o_e(emac1_gmii_mdo_o_e),
    .emac1_phy_mac_speed_o(emac1_phy_mac_speed_o),
    .emac1_phy_txclk_o_hio(emac1_phy_txclk_o_hio),
    .emac1_phy_txd_gmii_o(emac1_phy_txd_gmii_o),
    .emac1_phy_txd_o(emac1_phy_txd_o),
    .emac1_phy_txen_o(emac1_phy_txen_o),
    .emac1_phy_txer_o(emac1_phy_txer_o),
    .emac1_ptp_pps_o(emac1_ptp_pps_o),
    .emac1_rst_clk_rx_n_o(emac1_rst_clk_rx_n_o),
    .emac1_rst_clk_tx_n_o(emac1_rst_clk_tx_n_o),
    .s2f_emac1_ptp_tstmp_data(s2f_emac1_ptp_tstmp_data),
    .s2f_emac1_ptp_tstmp_en(s2f_emac1_ptp_tstmp_en),
    .emac2_gmii_mdi_i(emac2_gmii_mdi_i),
    .emac2_phy_col_i(emac2_phy_col_i),
    .emac2_phy_crs_i(emac2_phy_crs_i),
    .emac2_phy_rxclk_i(emac2_phy_rxclk_i),
    .emac2_phy_rxd_i(emac2_phy_rxd_i),
    .emac2_phy_rxdv_i(emac2_phy_rxdv_i),
    .emac2_phy_rxer_i(emac2_phy_rxer_i),
    .emac2_phy_txclk_i(emac2_phy_txclk_i),
    .emac2_ptp_aux_ts_trig_i(emac2_ptp_aux_ts_trig_i),
    .emac2_gmii_mdc_o(emac2_gmii_mdc_o),
    .emac2_gmii_mdo_o(emac2_gmii_mdo_o),
    .emac2_gmii_mdo_o_e(emac2_gmii_mdo_o_e),
    .emac2_phy_mac_speed_o(emac2_phy_mac_speed_o),
    .emac2_phy_txclk_o_hio(emac2_phy_txclk_o_hio),
    .emac2_phy_txd_gmii_o(emac2_phy_txd_gmii_o),
    .emac2_phy_txd_o(emac2_phy_txd_o),
    .emac2_phy_txen_o(emac2_phy_txen_o),
    .emac2_phy_txer_o(emac2_phy_txer_o),
    .emac2_ptp_pps_o(emac2_ptp_pps_o),
    .emac2_rst_clk_rx_n_o(emac2_rst_clk_rx_n_o),
    .emac2_rst_clk_tx_n_o(emac2_rst_clk_tx_n_o),
    .s2f_emac2_ptp_tstmp_data(s2f_emac2_ptp_tstmp_data),
    .s2f_emac2_ptp_tstmp_en(s2f_emac2_ptp_tstmp_en),
    .nand_adq_i(nand_adq_i),
    .nand_rdy_busy_i(nand_rdy_busy_i),
    .nand_adq_o(nand_adq_o),
    .nand_adq_oe(nand_adq_oe),
    .nand_ale_o(nand_ale_o),
    .nand_ce_n_o(nand_ce_n_o),
    .nand_cle_o(nand_cle_o),
    .nand_re_n_o(nand_re_n_o),
    .nand_we_n_o(nand_we_n_o),
    .nand_wp_n_o(nand_wp_n_o),
    .sdmmc_card_intn_i(sdmmc_card_intn_i),
    .sdmmc_cdn_i(sdmmc_cdn_i),
    .sdmmc_cmd_i(sdmmc_cmd_i),
    .sdmmc_data_i(sdmmc_data_i),
    .sdmmc_wp_i(sdmmc_wp_i),
    .sdmmc_cclk_o(sdmmc_cclk_o),
    .sdmmc_cmd_o(sdmmc_cmd_o),
    .sdmmc_cmd_oe(sdmmc_cmd_oe),
    .sdmmc_data_o(sdmmc_data_o),
    .sdmmc_data_oe(sdmmc_data_oe),
    .sdmmc_pwr_ena_o(sdmmc_pwr_ena_o),
    .sdmmc_rstn_o(sdmmc_rstn_o),
    .sdmmc_vs_o(sdmmc_vs_o),
    .spim0_miso_i(spim0_miso_i),
    .spim0_ss_in_n(spim0_ss_in_n),
    .spim0_mosi_o(spim0_mosi_o),
    .spim0_mosi_oe(spim0_mosi_oe),
    .spim0_sclk_out_hio(spim0_sclk_out_hio),
    .spim0_ss0_n_o(spim0_ss0_n_o),
    .spim0_ss1_n_o(spim0_ss1_n_o),
    .spim0_ss2_n_o(spim0_ss2_n_o),
    .spim0_ss3_n_o(spim0_ss3_n_o),
    .spim1_miso_i(spim1_miso_i),
    .spim1_ss_in_n(spim1_ss_in_n),
    .spim1_mosi_o(spim1_mosi_o),
    .spim1_mosi_oe(spim1_mosi_oe),
    .spim1_sclk_out_hio(spim1_sclk_out_hio),
    .spim1_ss0_n_o(spim1_ss0_n_o),
    .spim1_ss1_n_o(spim1_ss1_n_o),
    .spim1_ss2_n_o(spim1_ss2_n_o),
    .spim1_ss3_n_o(spim1_ss3_n_o),
    .spis0_clk(spis0_clk),
    .spis0_mosi_i(spis0_mosi_i),
    .spis0_ss_in_n(spis0_ss_in_n),
    .spis0_miso_o(spis0_miso_o),
    .spis0_miso_oe(spis0_miso_oe),
    .spis1_clk(spis1_clk),
    .spis1_mosi_i(spis1_mosi_i),
    .spis1_ss_in_n(spis1_ss_in_n),
    .spis1_miso_o(spis1_miso_o),
    .spis1_miso_oe(spis1_miso_oe),
    .uart0_cts_n(uart0_cts_n),
    .uart0_dcd_n(uart0_dcd_n),
    .uart0_dsr_n(uart0_dsr_n),
    .uart0_ri_n(uart0_ri_n),
    .uart0_rx(uart0_rx),
    .uart0_dtr_n(uart0_dtr_n),
    .uart0_out1_n(uart0_out1_n),
    .uart0_out2_n(uart0_out2_n),
    .uart0_rts_n(uart0_rts_n),
    .uart0_tx(uart0_tx),
    .uart1_cts_n(uart1_cts_n),
    .uart1_dcd_n(uart1_dcd_n),
    .uart1_dsr_n(uart1_dsr_n),
    .uart1_ri_n(uart1_ri_n),
    .uart1_rx(uart1_rx),
    .uart1_dtr_n(uart1_dtr_n),
    .uart1_out1_n(uart1_out1_n),
    .uart1_out2_n(uart1_out2_n),
    .uart1_rts_n(uart1_rts_n),
    .uart1_tx(uart1_tx),
    .i2c0_scl_i(i2c0_scl_i),
    .i2c0_sda_i(i2c0_sda_i),
    .i2c0_scl_oe(i2c0_scl_oe),
    .i2c0_sda_oe(i2c0_sda_oe),
    .i2c1_scl_i(i2c1_scl_i),
    .i2c1_sda_i(i2c1_sda_i),
    .i2c1_scl_oe(i2c1_scl_oe),
    .i2c1_sda_oe(i2c1_sda_oe),
    .i2c_emac0_scl_i(i2c_emac0_scl_i),
    .i2c_emac0_sda_i(i2c_emac0_sda_i),
    .i2c_emac0_scl_oe(i2c_emac0_scl_oe),
    .i2c_emac0_sda_oe(i2c_emac0_sda_oe),
    .i2c_emac1_scl_i(i2c_emac1_scl_i),
    .i2c_emac1_sda_i(i2c_emac1_sda_i),
    .i2c_emac1_scl_oe(i2c_emac1_scl_oe),
    .i2c_emac1_sda_oe(i2c_emac1_sda_oe),
    .i2c_emac2_scl_i(i2c_emac2_scl_i),
    .i2c_emac2_sda_i(i2c_emac2_sda_i),
    .i2c_emac2_scl_oe(i2c_emac2_scl_oe),
    .i2c_emac2_sda_oe(i2c_emac2_sda_oe),
    .tpiu_trace_clkin(tpiu_trace_clkin),
    .tpiu_trace_ctl(tpiu_trace_ctl),
    .tpiu_trace_clk_hio(tpiu_trace_clk_hio),
    .tpiu_trace_data(tpiu_trace_data),
    .soc2fpga_ar_ready(soc2fpga_ar_ready),
    .soc2fpga_aw_ready(soc2fpga_aw_ready),
    .soc2fpga_b_valid(soc2fpga_b_valid),
    .soc2fpga_clk(soc2fpga_clk),
    .soc2fpga_port_size_config_0(soc2fpga_port_size_config_0),
    .soc2fpga_port_size_config_1(soc2fpga_port_size_config_1),
    .soc2fpga_r_last(soc2fpga_r_last),
    .soc2fpga_r_valid(soc2fpga_r_valid),
    .soc2fpga_w_ready(soc2fpga_w_ready),
    .soc2fpga_b_id(soc2fpga_b_id),
    .soc2fpga_b_resp(soc2fpga_b_resp),
    .soc2fpga_r_data(soc2fpga_r_data),
    .soc2fpga_r_id(soc2fpga_r_id),
    .soc2fpga_r_resp(soc2fpga_r_resp),
    .soc2fpga_ar_lock(soc2fpga_ar_lock),
    .soc2fpga_ar_valid(soc2fpga_ar_valid),
    .soc2fpga_aw_lock(soc2fpga_aw_lock),
    .soc2fpga_aw_valid(soc2fpga_aw_valid),
    .soc2fpga_b_ready(soc2fpga_b_ready),
    .soc2fpga_r_ready(soc2fpga_r_ready),
    .soc2fpga_w_last(soc2fpga_w_last),
    .soc2fpga_w_valid(soc2fpga_w_valid),
    .soc2fpga_ar_addr(soc2fpga_ar_addr),
    .soc2fpga_ar_burst(soc2fpga_ar_burst),
    .soc2fpga_ar_cache(soc2fpga_ar_cache),
    .soc2fpga_ar_id(soc2fpga_ar_id),
    .soc2fpga_ar_len(soc2fpga_ar_len),
    .soc2fpga_ar_prot(soc2fpga_ar_prot),
    .soc2fpga_ar_size(soc2fpga_ar_size),
    .soc2fpga_aw_addr(soc2fpga_aw_addr),
    .soc2fpga_aw_burst(soc2fpga_aw_burst),
    .soc2fpga_aw_cache(soc2fpga_aw_cache),
    .soc2fpga_aw_id(soc2fpga_aw_id),
    .soc2fpga_aw_len(soc2fpga_aw_len),
    .soc2fpga_aw_prot(soc2fpga_aw_prot),
    .soc2fpga_aw_size(soc2fpga_aw_size),
    .soc2fpga_w_data(soc2fpga_w_data),
    .soc2fpga_w_strb(soc2fpga_w_strb),
    .lwsoc2fpga_ar_ready(lwsoc2fpga_ar_ready),
    .lwsoc2fpga_aw_ready(lwsoc2fpga_aw_ready),
    .lwsoc2fpga_b_valid(lwsoc2fpga_b_valid),
    .lwsoc2fpga_clk(lwsoc2fpga_clk),
    .lwsoc2fpga_port_size_config_0(lwsoc2fpga_port_size_config_0),
    .lwsoc2fpga_r_last(lwsoc2fpga_r_last),
    .lwsoc2fpga_r_valid(lwsoc2fpga_r_valid),
    .lwsoc2fpga_w_ready(lwsoc2fpga_w_ready),
    .lwsoc2fpga_b_id(lwsoc2fpga_b_id),
    .lwsoc2fpga_b_resp(lwsoc2fpga_b_resp),
    .lwsoc2fpga_r_data(lwsoc2fpga_r_data),
    .lwsoc2fpga_r_id(lwsoc2fpga_r_id),
    .lwsoc2fpga_r_resp(lwsoc2fpga_r_resp),
    .lwsoc2fpga_ar_lock(lwsoc2fpga_ar_lock),
    .lwsoc2fpga_ar_valid(lwsoc2fpga_ar_valid),
    .lwsoc2fpga_aw_lock(lwsoc2fpga_aw_lock),
    .lwsoc2fpga_aw_valid(lwsoc2fpga_aw_valid),
    .lwsoc2fpga_b_ready(lwsoc2fpga_b_ready),
    .lwsoc2fpga_r_ready(lwsoc2fpga_r_ready),
    .lwsoc2fpga_w_last(lwsoc2fpga_w_last),
    .lwsoc2fpga_w_valid(lwsoc2fpga_w_valid),
    .lwsoc2fpga_ar_addr(lwsoc2fpga_ar_addr),
    .lwsoc2fpga_ar_burst(lwsoc2fpga_ar_burst),
    .lwsoc2fpga_ar_cache(lwsoc2fpga_ar_cache),
    .lwsoc2fpga_ar_id(lwsoc2fpga_ar_id),
    .lwsoc2fpga_ar_len(lwsoc2fpga_ar_len),
    .lwsoc2fpga_ar_prot(lwsoc2fpga_ar_prot),
    .lwsoc2fpga_ar_size(lwsoc2fpga_ar_size),
    .lwsoc2fpga_aw_addr(lwsoc2fpga_aw_addr),
    .lwsoc2fpga_aw_burst(lwsoc2fpga_aw_burst),
    .lwsoc2fpga_aw_cache(lwsoc2fpga_aw_cache),
    .lwsoc2fpga_aw_id(lwsoc2fpga_aw_id),
    .lwsoc2fpga_aw_len(lwsoc2fpga_aw_len),
    .lwsoc2fpga_aw_prot(lwsoc2fpga_aw_prot),
    .lwsoc2fpga_aw_size(lwsoc2fpga_aw_size),
    .lwsoc2fpga_w_data(lwsoc2fpga_w_data),
    .lwsoc2fpga_w_strb(lwsoc2fpga_w_strb));

endmodule

// Description:
// This is a simple four-stage pipeline for connecting the MPFE ATB 
// (AMBA Trace Bus) master port to the HPS slave port.  
module mpfe_atb_pipeline (
   input atclk,
   input atrstn,

   input  [1:0] atbytes_m,
   input [31:0] atdata_m,
   input  [6:0] atid_m,
   input        atvalid_m,
   output       atready_m,
 
   output       afvalid_m,
   input        afready_m, 

   output       syncreq_m,

   output  [1:0] atbytes_s,
   output [31:0] atdata_s,
   output  [6:0] atid_s,
   output        atvalid_s,
   input         atready_s,
 
   input        afvalid_s,
   output       afready_s, 

   input        syncreq_s );

   localparam DEPTH = 4;

   reg  [1:0] atbytes [DEPTH-1:0];
   reg [31:0] atdata  [DEPTH-1:0];
   reg  [6:0] atid    [DEPTH-1:0];
   reg        atvalid [DEPTH-1:0];
   reg        atready [DEPTH-1:0];
 
   reg        afvalid [DEPTH-1:0];
   reg        afready [DEPTH-1:0];

   reg        syncreq [DEPTH-1:0];

   genvar i; 

   generate
      for (i=0; i<DEPTH; i=i+1) begin  :  pipeline
         always @(posedge atclk or negedge atrstn) begin
            if ( ~atrstn ) begin
                  atvalid[i] <= 0;
                  atready[i] <= 0;

                  afvalid[i] <= 0;
                  afready[i] <= 0;
          
                  syncreq[i] <= 0;
            end else begin
               if (i==0) begin
                  atbytes[0] <= atbytes_m;
                  atdata[0]  <= atdata_m;
                  atid[0]    <= atid_m;
                  atvalid[0] <= atvalid_m;
                  atready[0] <= atready_s;
 
                  afvalid[0] <= afvalid_s;
                  afready[0] <= afready_m;

                  syncreq[0] <= syncreq_s;
               end else begin
                  atbytes[i] <= atbytes[i-1];
                  atdata[i]  <= atdata[i-1];
                  atid[i]    <= atid[i-1];
                  atvalid[i] <= atvalid[i-1];
                  atready[i] <= atready[i-1];
 
                  afvalid[i] <= afvalid[i-1];
                  afready[i] <= afready[i-1];

                  syncreq[i] <= syncreq[i-1];
               end
            end
         end
      end
   endgenerate 

   assign atready_m  = atready[DEPTH-1]; 
   assign afvalid_m  = afvalid[DEPTH-1]; 
   assign syncreq_m  = syncreq[DEPTH-1]; 
   assign atbytes_s  = atbytes[DEPTH-1];
   assign atdata_s   = atdata[DEPTH-1];
   assign atid_s     = atid[DEPTH-1];
   assign atvalid_s  = atvalid[DEPTH-1]; 
   assign afready_s  = afready[DEPTH-1];

endmodule


