#ifndef _ALTERA_AGILEX_HPS_H_
#define _ALTERA_AGILEX_HPS_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'qsys_top_r1' in
 * file './qsys_top_r1/qsys_top_r1.sopcinfo'.
 */

/*
 * This file contains macros for module 'agilex_hps' and devices
 * connected to the following master:
 *   h2f_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'prbs_generator_1', class 'prbs_generator'
 * The macros are prefixed with 'PRBS_GENERATOR_1_'.
 * The prefix is the slave descriptor.
 */
#define PRBS_GENERATOR_1_COMPONENT_TYPE prbs_generator
#define PRBS_GENERATOR_1_COMPONENT_NAME prbs_generator_1
#define PRBS_GENERATOR_1_BASE 0x0
#define PRBS_GENERATOR_1_SPAN 32
#define PRBS_GENERATOR_1_END 0x1f

/*
 * Macros for device 'pio_0', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_0_'.
 * The prefix is the slave descriptor.
 */
#define PIO_0_COMPONENT_TYPE altera_avalon_pio
#define PIO_0_COMPONENT_NAME pio_0
#define PIO_0_BASE 0x3000
#define PIO_0_SPAN 16
#define PIO_0_END 0x300f
#define PIO_0_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_0_CAPTURE 0
#define PIO_0_DATA_WIDTH 2
#define PIO_0_DO_TEST_BENCH_WIRING 0
#define PIO_0_DRIVEN_SIM_VALUE 0
#define PIO_0_EDGE_TYPE NONE
#define PIO_0_FREQ 100000000
#define PIO_0_HAS_IN 0
#define PIO_0_HAS_OUT 1
#define PIO_0_HAS_TRI 0
#define PIO_0_IRQ_TYPE NONE
#define PIO_0_RESET_VALUE 0

/*
 * Macros for device 'ram_controller_1', class 'ram_controller'
 * The macros are prefixed with 'RAM_CONTROLLER_1_'.
 * The prefix is the slave descriptor.
 */
#define RAM_CONTROLLER_1_COMPONENT_TYPE ram_controller
#define RAM_CONTROLLER_1_COMPONENT_NAME ram_controller_1
#define RAM_CONTROLLER_1_BASE 0x30000
#define RAM_CONTROLLER_1_SPAN 32
#define RAM_CONTROLLER_1_END 0x3001f


#endif /* _ALTERA_AGILEX_HPS_H_ */
