#ifndef _ALTERA_QSYS_TOP_R1_H_
#define _ALTERA_QSYS_TOP_R1_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'qsys_top_r1' in
 * file './qsys_top_r1/qsys_top_r1.sopcinfo'.
 */

/*
 * This file contains macros for all modules with masters in the system and
 * all the devices connected to those masters.
 * Macro names have unique prefixes to prevent duplicate names.
 */

/*
 * Macros for device 'prbs_generator_1', class 'prbs_generator'
 * Path to the device is from the master group 'agilex_hps'.
 * The macros are prefixed with 'AGILEX_HPS_PRBS_GENERATOR_1_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define AGILEX_HPS_PRBS_GENERATOR_1_COMPONENT_TYPE prbs_generator
#define AGILEX_HPS_PRBS_GENERATOR_1_COMPONENT_NAME prbs_generator_1
#define AGILEX_HPS_PRBS_GENERATOR_1_BASE 0x0
#define AGILEX_HPS_PRBS_GENERATOR_1_SPAN 32
#define AGILEX_HPS_PRBS_GENERATOR_1_END 0x1f

/*
 * Macros for device 'pio_0', class 'altera_avalon_pio'
 * Path to the device is from the master group 'agilex_hps'.
 * The macros are prefixed with 'AGILEX_HPS_PIO_0_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define AGILEX_HPS_PIO_0_COMPONENT_TYPE altera_avalon_pio
#define AGILEX_HPS_PIO_0_COMPONENT_NAME pio_0
#define AGILEX_HPS_PIO_0_BASE 0x3000
#define AGILEX_HPS_PIO_0_SPAN 16
#define AGILEX_HPS_PIO_0_END 0x300f
#define AGILEX_HPS_PIO_0_BIT_CLEARING_EDGE_REGISTER 0
#define AGILEX_HPS_PIO_0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define AGILEX_HPS_PIO_0_CAPTURE 0
#define AGILEX_HPS_PIO_0_DATA_WIDTH 2
#define AGILEX_HPS_PIO_0_DO_TEST_BENCH_WIRING 0
#define AGILEX_HPS_PIO_0_DRIVEN_SIM_VALUE 0
#define AGILEX_HPS_PIO_0_EDGE_TYPE NONE
#define AGILEX_HPS_PIO_0_FREQ 100000000
#define AGILEX_HPS_PIO_0_HAS_IN 0
#define AGILEX_HPS_PIO_0_HAS_OUT 1
#define AGILEX_HPS_PIO_0_HAS_TRI 0
#define AGILEX_HPS_PIO_0_IRQ_TYPE NONE
#define AGILEX_HPS_PIO_0_RESET_VALUE 0

/*
 * Macros for device 'ram_controller_1', class 'ram_controller'
 * Path to the device is from the master group 'agilex_hps'.
 * The macros are prefixed with 'AGILEX_HPS_RAM_CONTROLLER_1_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define AGILEX_HPS_RAM_CONTROLLER_1_COMPONENT_TYPE ram_controller
#define AGILEX_HPS_RAM_CONTROLLER_1_COMPONENT_NAME ram_controller_1
#define AGILEX_HPS_RAM_CONTROLLER_1_BASE 0x30000
#define AGILEX_HPS_RAM_CONTROLLER_1_SPAN 32
#define AGILEX_HPS_RAM_CONTROLLER_1_END 0x3001f

/*
 * Macros for device 'agilex_hps', class 'intel_agilex_hps'
 * Path to the device is from the master group 'pattern_writer_1'.
 * The macros are prefixed with 'PATTERN_WRITER_1_AGILEX_HPS_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define PATTERN_WRITER_1_AGILEX_HPS_COMPONENT_TYPE intel_agilex_hps
#define PATTERN_WRITER_1_AGILEX_HPS_COMPONENT_NAME agilex_hps
#define PATTERN_WRITER_1_AGILEX_HPS_BASE 0x0
#define PATTERN_WRITER_1_AGILEX_HPS_SPAN 0x0
#define PATTERN_WRITER_1_AGILEX_HPS_END 0xffffffff


#endif /* _ALTERA_QSYS_TOP_R1_H_ */
