// user_rst_clkgate_0.v

// Generated using ACDS version 22.4 94

`timescale 1 ps / 1 ps
module user_rst_clkgate_0 (
		output wire  ninit_done  // ninit_done.ninit_done
	);

	altera_s10_user_rst_clkgate altera_s10_user_rst_clkgate_inst (
		.ninit_done (ninit_done)  //  output,  width = 1, ninit_done.ninit_done
	);

endmodule
